"""Init v1 schema

Revision ID: 6d98af97a0e5
Revises: 
Create Date: 2026-06-10 15:52:13.627506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d98af97a0e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_ip_alerts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('attacker_ip', postgresql.INET(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('distinct_source_count', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'open'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attacker_ip')
    )
    op.create_table('sensor_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), server_default=sa.text("'#FF0000'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )

    sensor_types_table = sa.table(
        "sensor_types",
        sa.column("code", sa.String(length=50)),
        sa.column("label", sa.String(length=150)),
        sa.column("category", sa.String(length=100)),
        sa.column("color", sa.String(length=7)),
    )

    op.bulk_insert(
        sensor_types_table,
        [
            {
                "code": "lurio",
                "label": "Lurio Honeypot",
                "category": "leurre",
                "color": "#4A5D4E",
            },
            {
                "code": "detoxio",
                "label": "Detoxio",
                "category": "détection",
                "color": "#A8C2C0",
            },
            {
                "code": "waf",
                "label": "Web Application Firewall",
                "category": "protection",
                "color": "#E5DCD3",
            },
        ],
    )

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_type_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('color', sa.String(length=7), server_default=sa.text("'#FF0000'"), nullable=False),
    sa.ForeignKeyConstraint(['sensor_type_id'], ['sensor_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sensor_type_id', 'external_id')
    )
    op.create_index('idx_sources_sensor_type_id', 'sources', ['sensor_type_id'], unique=False)
    
    op.create_table('attacks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deduplication_id', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_event_id', sa.String(length=150), nullable=True),
    sa.Column('attacker_ip', postgresql.INET(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('attack_type', sa.String(length=100), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='status_correlation'), server_default=sa.text("'pending'"), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deduplication_id')
    )
    op.create_index('idx_attacks_attacker_ip', 'attacks', ['attacker_ip'], unique=False)
    op.create_index('idx_attacks_occurred_at', 'attacks', [sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index('idx_attacks_pending_occurred_at', 'attacks', ['occurred_at', 'id'], unique=False, postgresql_where=sa.text("correlation_status = 'pending'"))
    op.create_index('idx_attacks_source_occurred_at', 'attacks', ['source_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index('idx_attacks_type_occurred_at', 'attacks', ['attack_type', sa.literal_column('occurred_at DESC')], unique=False, postgresql_where=sa.text('attack_type IS NOT NULL'))
    op.create_table('common_ip_alert_sources',
    sa.Column('alert_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hit_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['common_ip_alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('alert_id', 'source_id')
    )
    op.create_table('scheduler_state',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('last_inventory_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduler_state')
    op.drop_table('common_ip_alert_sources')
    op.drop_index('idx_attacks_type_occurred_at', table_name='attacks', postgresql_where=sa.text('attack_type IS NOT NULL'))
    op.drop_index('idx_attacks_source_occurred_at', table_name='attacks')
    op.drop_index('idx_attacks_pending_occurred_at', table_name='attacks', postgresql_where=sa.text("correlation_status = 'pending'"))
    op.drop_index('idx_attacks_occurred_at', table_name='attacks')
    op.drop_index('idx_attacks_attacker_ip', table_name='attacks')
    op.drop_table('attacks')
    op.execute("DROP TYPE IF EXISTS status_correlation")
    op.drop_index('idx_sources_sensor_type_id', table_name='sources')
    op.drop_table('sources')
    op.drop_table('sensor_types')
    op.drop_table('common_ip_alerts')
    # ### end Alembic commands ###
